spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/datashare
spring.datasource.username=datashare
spring.datasource.password=datashare
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
app.jwt.secret=CHANGE_ME_SUPER_SECRET_KEY_CHANGE_ME_SUPER_SECRET_KEY
app.jwt.expiration-ms=86400000

# File upload configuration
app.file.expiration-days=7
app.file.max-size=1073741824
app.file.allowed-types=text/plain,application/pdf,image/png,image/jpeg,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation

# File expiration scheduler
app.file.expiration-cron=0 0 * * * *

logging.level.com.datashare.backend=DEBUG


# Spring multipart limits
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1100MB
